### PR TITLE
Feature/logging

### PR DESCRIPTION
**Pull request by ALobker**

### CODE REVIEW

**Comment by ALobker** [comment]
Pub/sub is for one sender and many receivers. Logging is the other way around.

**Comment by iiKoe** [comment]
@ALobker No, an observer is one sender and many receivers (one-to-many), In pub/sub many to many is possible due to broadcasts etc.

> In software architecture, publish–subscribe is a messaging pattern where senders of messages, called publishers, do not program the messages to be sent directly to specific receivers, called subscribers, but instead characterize published messages into classes without knowledge of which subscribers, if any, there may be. Similarly, subscribers express interest in one or more classes and only receive messages that are of interest, without knowledge of which publishers, if any, there are.

**Comment by ALobker** [comment]
This would require the logger to subscribe to all classes that may want to log something.

Anyways, this pattern is way to complicated for our use.

**Comment by iiKoe** [comment]
@ALobker 
That's why I suggested topics like ERROR, WARN, INFO etc, jeromq supports all this (java version of zeromq). But after re-reading the assignment I do agree that this might be overboard as it stated to make a "simple logger" :(

And I see it also says: "without using any existing logging library", even tough jeromq is a message passing library, this might be received as not ok.

I would like to incorporate types in the logging, so a different "deepness" can be selected (think -v -vv -vvv in allot of programs) So for example ERROR, WARN, INFO, DEBUG (just have it as an enum or something) . We could also make logger an abstract class so we can create different loggers (to file and to console for example). This also makes us use the Template design Pattern.
We can only define which one we want before we start logging, but that's OK for a simple logger.
(that's why I wanted the jeromq pub/sub initially, so we can have multiple loggers receiving the same tags. So we can log to a file AND to console in a nice way, but again true that its kinda overkill for a "simple logger").

**Pull request closed without merging**
